apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    components: {{ .Values.app.components }}
