apiVersion: v1
kind: Secret
metadata:
  name: short-api-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RlbW86ZGVtb0Bwb3N0Z3Jlcy1jbHVzdGVyaXA6NTQzMi9kZW1vCg==

# DATABASE_URL: postgresql://user:password@url:port/db
# ~echo postgresql://demo:demo@postgres-clusterip:5432/demo | base64