apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      labels:
        components: frontend
    spec:
      containers:
      - name: short-api
        image: antonlarichev/short-api:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        env:
         - name: DATABASE_URL
           valueFrom:
            secretKeyRef:
              name: short-api-secret
              key: DATABASE_URL

