apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
      - name: short-app
        image: antonlarichev/short-app:v1.4
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
